version: '3'
services:
  
  ##########################################################################################
  ### Kafka connect by localhost:9092 in network microservices, volume for data
  ##########################################################################################
  
  kafka:
    image: confluentinc/cp-kafka:6.2.5
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - microservices
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'
    networks:
      - microservices

  ##########################################################################################
  ### Redis 7.2-alpine db 0
  ########################################################################################## 

  redis-queue:
    image: redis:7.2-alpine
    ports:
      - '${PORT_REDIS}:${PORT_REDIS}'
    volumes:
      - redis_queue_data:/data
    networks:
      - microservices
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes

  ##########################################################################################
  ### Backend
  ##########################################################################################

  ginapi-gateway:
    build: ./app
    ports:
      - '${PORT_GINAPI_GATEWAY}:${PORT_GINAPI_GATEWAY}'
    volumes:
      - ./.env:/app/.env
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  redis_queue_data:
  kafka_data: